### ISSUE TITLE
PrairieGrader v2 planning

### ISSUE THREAD

**Issue by nwalters512** [PrairieLearn/PrairieGrader#40]
PG has been running just about flawlessly for a fair amount of time now, but there's still room for improvement here. I'd like to start thinking about what v2 could look like.

The main pain point I want to improve is the case where a job lands on a machine that doesn't have the necessary image. We're scheduling jobs completely blindly here, which is nice for the sake of simplicity, but results in significantly delays in the previously mentioned case.

My idea for fixing this is to turn this into a distributed system with a coordinator that knows about the state of all the workers: what images they have, what jobs they're running, etc. We submit jobs to the coordinator and it'll do rudimentary scheduling by trying to place jobs on workers that already have the necessary image. We could also tell workers to begin pulling images while they're working on another job.

We could also do clever things like moving images via P2P transfer. Not sure if this would be better or worse than the Docker pull-through cache. But I believe this is what Zeit does for Now.

Concerns:
* Complexity: this would introduce a lot of moving pieces.
* Brittleness: moving pieces means more potential for things to break.
* Local dev: having all workers interact directly with the queue is very nice for local dev.
* Distributed scheduling: hard.

The more I write about this, the more I wonder if it's worth it. The benefits would be relatively small - the average execution time would hopefully stay about the same, this would just hopefully decrease the max. Is this a problem we want to try to solve?

Let's discuss!

**Comment by mwest1066** [comment]
Our discussion yesterday convinced me that micro-managing each grader VM is going to be a nightmare. That is, attempting to keep track of which graders have which container images pulled, and trying to load-balance on that level, is just too hard.

The conclusion we reached yesterday about load-balancing in pools seems good. Just to summarize, we group grading containers into pools (by default, one pool per university or something like that) and the rule is that all grader VMs in the pool will pull all container images for that pool. Then load balancing is done per-pool, using exactly our current system. There is one SQS queue per pool.

Some things we could do to make this work even better than it does at the moment:

1. Have a communication channel between graders, so that when any grader pulls a new image it can tell all the other graders and they can immediately start pulling it too. I'm not sure how best to implement this.

2. Use the same communication channel so that PL can tell all graders to pull a new image whenever a student views a question page with an externally graded question.

3. When a grader receives a job, it should first check whether it has the appropriate image ready to run. If not, it should put the job back onto the queue and start pulling the image. This will allow other graders that already have the image to process the job, or in the worst case the same grader will eventually get the job back again after it has the image. To put the job back on the queue, one easy way might be to wait for 1 second, call `changeMessageVisibility()` with a new timeout of 0 seconds, and then just drop the job locally. My understanding is that this re-queues the message without counting as a failure. It's a bit ugly, because it introduces at least 1 second of delay, and it might cause the message to be repeatedly received and then requeued, with a 1 second delay each time. But it has the advantage of being really simple. Alternatively, I guess we could re-queue the grading job as a new SQS message and then delete the old one.

**Comment by nwalters512** [comment]
This repo is being archived. If this is still relevant, please recreate it in the [`PrairieLearn/PrairieLearn`](https://github.com/PrairieLearn/PrairieLearn) repository.
